# Generated by Django 2.1.15 on 2023-05-03 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolivre', '0002_auto_20230428_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenmercadolivreapi',
            old_name='code',
            new_name='refresh_token_inicial',
        ),
        migrations.AddField(
            model_name='tokenmercadolivreapi',
            name='refresh_token_atualizado',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
