# Generated by Django 2.1.15 on 2023-05-03 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolivre', '0003_auto_20230503_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenmercadolivreapi',
            name='refresh_token_atualizado',
        ),
    ]
