# Generated by Django 2.1.15 on 2024-10-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercadolivre', '0004_remove_tokenmercadolivreapi_refresh_token_atualizado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenMercadoLivreFitGearAPI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refresh_token_inicial', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
            ],
        ),
    ]
