# Generated by Django 2.1.15 on 2023-04-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoNetshoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('termo_busca', models.CharField(max_length=255)),
                ('sku_netshoes', models.CharField(max_length=255)),
            ],
        ),
    ]
