# Generated by Django 2.1.15 on 2023-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicaonetshoes',
            name='posicao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
