# Generated by Django 2.1.15 on 2023-04-19 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0002_posicaonetshoes_posicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicaonetshoes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posicaonetshoes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
