# Generated by Django 2.1.15 on 2023-04-20 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0003_auto_20230419_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicaonetshoes',
            name='anuncio_concorrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posicaonetshoes',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posicaonetshoes',
            name='pagina',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
