# Generated by Django 2.1.15 on 2023-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0006_auto_20230420_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicaonetshoes',
            name='crescimento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
