# Generated by Django 2.1.15 on 2023-04-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0007_posicaonetshoes_crescimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicaonetshoes',
            name='ultima_atualizacao',
            field=models.DateTimeField(),
        ),
    ]
