# Generated by Django 2.1.15 on 2023-04-27 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0008_auto_20230427_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicaonetshoes',
            name='ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
