# Generated by Django 2.1.15 on 2023-04-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0010_auto_20230427_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicaonetshoes',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
