# Generated by Django 2.1.15 on 2023-04-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0011_auto_20230427_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicaonetshoes',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
