# Generated by Django 2.1.15 on 2023-04-28 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0012_auto_20230427_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posicaonetshoes',
            name='ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
