# Generated by Django 2.1.15 on 2023-05-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0013_auto_20230428_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posicaonetshoes',
            old_name='crescimento',
            new_name='variacao',
        ),
    ]
