# Generated by Django 2.1.15 on 2023-05-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0014_auto_20230504_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosicaoMercadoLivre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('termo_busca', models.CharField(max_length=255)),
                ('mlb_anuncio', models.CharField(max_length=255)),
                ('posicao', models.IntegerField(blank=True, null=True)),
                ('pagina', models.IntegerField(blank=True, null=True)),
                ('visita_diaria', models.FloatField(blank=True, null=True)),
                ('visita_total', models.IntegerField(blank=True, null=True)),
                ('vendas_diaria', models.FloatField(blank=True, null=True)),
                ('vendas_total', models.IntegerField(blank=True, null=True)),
                ('taxa_conversao_diaria', models.FloatField(blank=True, null=True)),
                ('taxa_conversao_total', models.FloatField(blank=True, null=True)),
                ('pontuacao_anuncio', models.FloatField(blank=True, null=True)),
                ('criacao_anuncio', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
