# Generated by Django 2.1.15 on 2023-05-04 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0016_auto_20230504_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricasmercadolivre',
            name='ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
