# Generated by Django 2.1.15 on 2023-05-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0018_metricasmercadolivre_vende_a_cada_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricasmercadolivre',
            name='pagina_full',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metricasmercadolivre',
            name='posicao_full',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
