# Generated by Django 2.1.15 on 2023-07-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0020_metricasads'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_interno', models.CharField(max_length=255)),
                ('vlr_custo_antigo', models.FloatField(blank=True, null=True)),
                ('vlr_custo_novo', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
