# Generated by Django 2.1.15 on 2023-07-05 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0021_pedidoscompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoscompra',
            name='descricao',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
