# Generated by Django 2.1.15 on 2023-07-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0022_pedidoscompra_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoscompra',
            old_name='cod_interno',
            new_name='COD_INTERNO',
        ),
        migrations.RenameField(
            model_name='pedidoscompra',
            old_name='descricao',
            new_name='DESCRICAO',
        ),
        migrations.RenameField(
            model_name='pedidoscompra',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='pedidoscompra',
            old_name='vlr_custo_antigo',
            new_name='VLR_CUSTO_ANTIGO',
        ),
        migrations.RenameField(
            model_name='pedidoscompra',
            old_name='vlr_custo_novo',
            new_name='VLR_CUSTO_NOVO',
        ),
    ]
