# Generated by Django 2.1.15 on 2023-07-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0023_auto_20230705_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoscompra',
            old_name='COD_INTERNO',
            new_name='cod_interno',
        ),
        migrations.RenameField(
            model_name='pedidoscompra',
            old_name='DESCRICAO',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='pedidoscompra',
            old_name='ID',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='pedidoscompra',
            old_name='VLR_CUSTO_ANTIGO',
            new_name='vlr_custo_antigo',
        ),
        migrations.RenameField(
            model_name='pedidoscompra',
            old_name='VLR_CUSTO_NOVO',
            new_name='vlr_custo_novo',
        ),
    ]
