# Generated by Django 2.1.15 on 2023-10-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0025_remove_pedidoscompra_vlr_custo_novo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoProdutoCadastrado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autoid', models.IntegerField()),
            ],
        ),
    ]
