# Generated by Django 2.1.15 on 2023-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0026_ultimoprodutocadastrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoProdutoCadastradoAton',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codid', models.IntegerField()),
            ],
        ),
    ]
