# Generated by Django 2.1.15 on 2024-03-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0027_ultimoprodutocadastradoaton'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchNetshoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_produto', models.CharField(max_length=255)),
                ('sku_match', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
