# Generated by Django 2.1.15 on 2024-03-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0029_matchnetshoes_nome_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchnetshoes',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
