# Generated by Django 2.1.15 on 2024-03-03 23:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0030_auto_20240303_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchnetshoes',
            name='ultima_atualizacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
