# Generated by Django 2.1.15 on 2024-09-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0031_matchnetshoes_ultima_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentauroTarifas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dagg_comissao_padrao', models.IntegerField()),
                ('operacao', models.IntegerField()),
                ('imposto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DecathlonTarifas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dagg_comissao_padrao', models.IntegerField()),
                ('operacao', models.IntegerField()),
                ('imposto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NetshoesTarifas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dagg_comissao_padrao', models.IntegerField()),
                ('red_comissao_padrao', models.IntegerField()),
                ('pisste_comissao_padrao', models.IntegerField()),
                ('tarifa_fixa', models.IntegerField()),
                ('operacao', models.IntegerField()),
                ('imposto', models.IntegerField()),
            ],
        ),
    ]
