# Generated by Django 2.1.15 on 2024-10-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackeamento', '0032_centaurotarifas_decathlontarifas_netshoestarifas'),
    ]

    operations = [
        migrations.AddField(
            model_name='posicaonetshoes',
            name='canal',
            field=models.CharField(choices=[('MADZ', 'MADZ'), ('LEAL', 'LEAL'), ('PISSTE', 'PISSTE')], default='MADZ', max_length=20),
        ),
    ]
