# Generated by Django 2.1.15 on 2023-11-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0002_registroclique'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUltimoBalanco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_interno', models.CharField(max_length=120)),
                ('data_e_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
